services:
  - type: web
    name: lighthouse-anniversary
    runtime: node
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/wishes
    plan: free
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
